### ISSUE TITLE
Add some information in README file

### ISSUE THREAD

**Issue by vbauer** [ffgiraldez/Migratron#1]

**Comment by ffgiraldez** [comment]
this was a little pet project to learn how to upload libraries into maven central.

it's glad to see that someone it's interested in the project too, I will update the README as soon as I can

**Comment by vbauer** [comment]
Thanks in advance!

**Comment by Kisty** [comment]
Love the look of this library. Would be great to have an example app or example code to show its usage and explain clearly what problem it solves, which I think I get but some might not.

Is it to help with database versioning, new moving/introducing new shared preferences, changing default preferences, etc? How do you personally use the library?
